### ISSUE TITLE
Board pinout

### ISSUE THREAD

**Issue by faronov** [zanjie1999/esp32-st7789v-ft6236u-arduino#2]
Did you use the same board from 老王电子数码DIY ?
![O1CN01JGJb4u1IeUOYbBRIE_!!1799820918](https://user-images.githubusercontent.com/5890505/220615613-f4f6e04f-9483-471b-925e-e46a7d76d851.jpeg)
Is this board correctly labeled pinout?

**Comment by zanjie1999** [comment]
Yep, but i use this screen:
https://www.bilibili.com/video/BV11g411W7cR
